### ISSUE TITLE
Gaming ballistics gurps qrs not compatible with last two stable versions

### ISSUE THREAD

**Issue by AndrewAJMT** [mjeffw/gurps-quick-reference-sheet#6]
I've only tried using latest two stable updates (12 Stable 329 and the one immediately before) but the module appears in the list but when checked it can't be activated.

This effects the bestiary and Saethors Bane VTT Modules. Neither can be activated.

The sheet defaults now to full GCS and works still, and a lot of the other sheet options work. So the Bestiary previously installed still works without the gurps qrs.

Think the problem might be connected with the GURPS 4e game aid (Unofficial) which won't update and seems to have a lot of issues at the moment.

Thanks for all the work everyone puts into this module and the other gaming ballistic modules!

**Comment by mjeffw** [comment]
If GGA won't update, delete it and redownload it. Then let's see if the quick reference sheet starts to work or not.

**Comment by AndrewAJMT** [comment]
Thank you! Problem solved.

When i came to delete, i noticed somehow it was locked - must have happened by accident. Anyway, it updated after being unlocked.

I think hte thing is foundry is great but for non-devs like me it can catch me out. It's still the best.

And thank you gain for this answer and for the work you do!
